### ISSUE TITLE
uBlock Origin integration

### ISSUE THREAD

**Issue by 0xD4** [Rob--W/dont-track-me-google#12]
Would it be possible to integrate the functionality of your plugin to work within uBlock Origin?

https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en
https://github.com/gorhill/uBlock/wiki/Dashboard:-3rd-party-filters
https://filterlists.com

**Comment by Rob--W** [comment]
No, that's not possible. My extension does not block URLs, it rewrites links in Google sites to make sure that Google does not convert the link to an "ugly" link (see my project's README).

**Comment by 0xD4** [comment]
OK, thanks.

Awesome plugin btw! Thank you for your effort!
