### ISSUE TITLE
Color of the redirection screen

### ISSUE THREAD

**Issue by someoneb100** [Rob--W/dont-track-me-google#13]
I use dark themes on almost all of the sites i use including google, and when i click on a link when this script is active the burst of sudden white burns my eyes... I know this is nitpicking but how should i edit the script for the screen to be black instead of white? I've been messing with the code for some time now, but i am just not good enough for the task... I am using the greasemonkey version.

**Comment by anewuser** [comment]
It isn't up to this extension to set the default background color of your browser.

You need to do it with the same method you are using to apply "themes" to websites.

I have this in my Firefox `userContent.css` file, where `#eee` is the [hex value of the color](https://meyerweb.com/eric/tools/color-blend/#EEEEEE:000000:10:hex):
>@-moz-document url(about:blank) {*:empty:not([style]):not([text]):not([class]):not([onresize]) {background-color: #eee;}}

**Comment by Rob--W** [comment]
My current release does not have any redirection screen any more. Where did you get the "greasemonkey version"?

For #3 I created a tool to create a user script from my extension's source code, but I have yet to find a good way to publish the user script.

**Comment by Rob--W** [comment]
Closing due to the lack of feedback and actionable task.
