### ISSUE TITLE
Submit to the Opera store

### ISSUE THREAD

**Issue by anewuser** [Rob--W/dont-track-me-google#14]
I installed your extension with [Download Chrome Extension](https://addons.opera.com/extensions/details/download-chrome-extension-9/) and it works as expected with apparently no issues.

You can [submit it to the Opera store](https://dev.opera.com/extensions/publishing-guidelines/) for users to enjoy automatic updates.

**Comment by Rob--W** [comment]
I'll do this somewhere in the future.

**Comment by Rob--W** [comment]
I've submitted my extension to Opera's add-on gallery. [The link](https://addons.opera.com/en/extensions/details/dont-track-me-google/) is 404 for now until they approve it.
