### ISSUE TITLE
Unrecognized manifest key 'applications'.

### ISSUE THREAD

**Issue by wickedsp1d3r** [Rob--W/dont-track-me-google#15]
I get this when I load the extension:

![capture](https://user-images.githubusercontent.com/1852854/27791385-6c448b1e-5ffd-11e7-9b4e-061120979c7c.png)

It does not affect the functionality of the extension, though.
Just to let you know.

**Comment by Rob--W** [comment]
It's harmless, but I've removed it since you're the second one to bring this up.
