### ISSUE TITLE
Gmail hijacks links

### ISSUE THREAD

**Issue by hickford** [Rob--W/dont-track-me-google#2]
Hi Rob. Gmail is still hijacking links in emails I receive. Here's an example:

    <a href="http://www.forgefix.co.uk/Products/lightning-bolts" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en-GB&amp;q=http://www.forgefix.co.uk/Products/lightning-bolts&amp;source=gmail&amp;ust=1469172403783000&amp;usg=AFQjCNH-MlbDsXYqI6FIoI6ntAxamRi7lg"><wbr>Products/lightning-bolts</a>

When I click the link for forgefix.co.uk, sleazy Gmail swaps it for the google.com URL

I'm using "Don't track me Google 4.4"

**Comment by Rob--W** [comment]
Finally I managed to reproduce your issue. Clicking on such a "link" does not cause the link to be followed; Gmail opens a new tab with the rewritten URL. This is the beatified code snippet that I identified:

```javascript
    Bw.prototype.ha = function(a) {
        var b;
        if (!a.defaultPrevented) {
            var c = jdb(this, a); // <-- Potentially an <a> element.
            c && (b = this.ra(c)); // <-- this extracts the value of data-saferedirecturl to b if set
            var d;
            if (d = c && b) {
                d = b;
                var e = this.window.getWindow().location.href;
                d = !(Ba(d, "javascript:") || "#" == d || "" == Gp(d) && Uq(d, e) && Tp(d) == Tp(e))
            }
            if (d) {
                b = Ja(b);
                d = !0;
                if (this.Ca(c, b))
                    d = !1;
                else if (e = c.getAttribute("href"),
                /^#/.test(e) && this.$A.ra.getElementsByName(e.substr(1)).item(0)) {
                    if (b = Oea(Gp(b)) || "",
                    b = this.$A.ra.getElementsByName(b).item(0))
                        this.yd.get(Yf).scrollIntoView(b, 2),
                        d = !1
                } else { // Ignore above, continue here.
                    var e = b
                      , g = this.window.getWindow().location.href;
                    Uq(e, g) && Tp(e) == Tp(g) ? (b = Gp(b) || "",
                    "" != b && (this.yd.get(Sf).bE(b),
                    d = !1)) : qg && Yc("532.5") && c.hasAttribute("rel") && "noreferrer" == c.getAttribute("rel") || this.Aa(a, b) ? d = !0 : (c = b,
                    qg && Yc("532.5") ? (b = this.$A.ra,
                    c = ue("a", {
                        href: c,
                        target: "_blank",
                        rel: "noreferrer",
                        style: "display: none"
                    }), // <-- Creates <a href="https://www.google.com/url?..." target="_blank" rel="noreferrer" style="display: none;"></a>
                    // NOTE: This appears to be running in the js_frame.
                    d = b.createEvent("MouseEvent"),
                    d.initMouseEvent("click", !0, !0, this.window.getWindow(), 0, a.screenX, a.screenY, a.clientX, a.clientY, a.ctrlKey, a.altKey, a.shiftKey, a.metaKey, a.button, a.relatedTarget),
                    we(b.body, c),
                    c.dispatchEvent(d), // <-- Forge click event to open new tab
                    Be(c)) : Aw(this.Ha, c, {
                        target: "_blank"
                    }, !0), // <-- Not activated, but if the click did not work this would open a popup
                    d = !1)
                }
                d || ((b = Wt(this.yh).gbar) && b.close && b.close(),
                a.preventDefault(),
                a.stopPropagation())
            }
        }
    }
```

Gmail basically creates a link in a (non-blank) child frame and clicks on it. I am only running in the main frame at the moment so the aggressive link rewriter did not kick in. I activated the script in the child frame and that fixed the issue.

**Comment by Rob--W** [comment]
Published as version 4.5, please update and confirm whether the issue has been resolved.

**Comment by hickford** [comment]
Thanks Rob. Version 4.5 solved my problem. I appreciate your time.

**Comment by Javarome** [comment]
It looks that Gmail now simulates a click only for mobile (ipad, iphone, ipod...) and on others just adds a meta refresh to let the  new window load its url.

**Comment by Rob--W** [comment]
> It looks that Gmail now simulates a click only for mobile (ipad, iphone, ipod...) and on others just adds a meta refresh to let the new window load its url.

Could you be a bit more specific? What browser (versions) and extensions are you using? What did you do, what did you observe and what did you expect instead?

**Comment by Javarome** [comment]
I investigated latest Gmail code for a similar issue and just wanted to share my findings, in case that might help to keep your work up to date.

**Comment by Rob--W** [comment]
Thanks for sharing. I am aware of it happening and my code already accounts for it; see the patches referenced in #41 (with a fixup in #45). The current code is at https://github.com/Rob--W/dont-track-me-google/blob/abffd08f6e0d6eacd42b3ff0ccda1b6838788949/contentscript.js#L384-L481

**Comment by Javarome** [comment]
Very nice. I used a more radical way of avoiding Google window.open by overriding as a failure/exception throwing. As a result the _blank link is just followed. 

However in Gmail they are currently not labeled with `rel="noopener,noreferrer"` so I had to add them on all `_blank` (assumed external) links (again that's a way more dumb workaround than yours).
