### ISSUE TITLE
Facebook tracking

### ISSUE THREAD

**Issue by KwarcPL** [Rob--W/dont-track-me-google#25]
FB works the same as Google Search. Don't you think that it would be nice to create something similar for it?

**Comment by Rob--W** [comment]
This was asked before in #9, and I am still of the opinion that I don't intent to support Facebook in the extension.

If you are concerned about Facebook's tracking, then (short of ditching Facebook alltogether) is to:

- Use a completely isolated browsing session (e.g. with Container tabs in Firefox).
- Completely block Facebook and its related websites in your other browser profiles.
