### ISSUE TITLE
Get listed as replacement of "Remove Google Tracking "

### ISSUE THREAD

**Issue by nemobis** [Rob--W/dont-track-me-google#26]
I'm using this extension with success and no complications (also together with uMatrix which disables some JavaScript).

https://addons.mozilla.org/en-US/firefox/addon/remove-google-tracking/ is not compatible with Firefox 57+ and it would be nice if its users found your extension by clicking the [corresponding "find a replacement" link](https://addons.mozilla.org/find-replacement/?guid=jid0-DpogclPgnN9OvqNntEBbPZxBinY@jetpack).

According to the notice on top of https://blog.mozilla.org/addons/2017/10/26/helping-find-compatible-extensions/ , you need to ask the addons.mozilla.org (AMO) admins/moderators at https://discourse.mozilla.org/t/favorite-webextensions/17087 

Thanks!

**Comment by Rob--W** [comment]
I have posted a replacement suggestion at https://discourse.mozilla.org/t/favorite-webextensions/17087/185

**Comment by Rob--W** [comment]
This seems to have happened.

https://addons.mozilla.org/find-replacement/?guid=jid0-DpogclPgnN9OvqNntEBbPZxBinY@jetpack
redirects to
https://addons.mozilla.org/en-US/firefox/addon/dont-track-me-google1/?src=find-replacement
