### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by nibbledeez** [Rob--W/dont-track-me-google#27]
At some point (I only noticed today) this extension stopped working for Google news which is a great shame as I have used it since it was a userscript!

![dtmg](https://user-images.githubusercontent.com/17723837/41657970-ebfec776-748c-11e8-9853-d0be8382bec9.png)

Tested version 4.2.1 on Vivaldi 1.16 and Chrome 67
ps. thank you for your work on it!

**Comment by Rob--W** [comment]
There is no obvious way to retrieve the real URL from the `<a>` link elements.

**Comment by nibbledeez** [comment]
Oh - thanks Rob - it *used* to work though, right?

**Comment by Rob--W** [comment]
I don't know, I don't use Google News.

**Comment by nibbledeez** [comment]
Ok - will close - thanks anyway.
