### ISSUE TITLE
Google Docs header links broken?

### ISSUE THREAD

**Issue by malyavkin** [Rob--W/dont-track-me-google#4]
This is how regular Google Docs link look like (In table of contents for example)

    <div class="docs-bubble docs-linkbubble-bubble" role="dialog" aria-label="Change or remove link." tabindex="0" style="direction: ltr; left: 244px; top: 1565px;">
        <a target="_blank" rel="noreferrer" href="#heading=h.pnvgauhbu6d6">#heading=h.pnvgauhbu6d6</a>
        <span> – 
            <span class="docs-bubble-link" role="button" tabindex="0">Change</span> | 
            <span class="docs-bubble-link" role="button" tabindex="0">Remove</span>
        </span>
    </div>

Looks like there's a script somewhere there that intercepts the click and scrolls to the header instead opening it in new tab. 

Well, it doesn't work if Don't track me Google is enabled -- it opens new tab for it. 

I'm using Don't track me Google 4.9 

ps: thanks, this extension is great

**Comment by Rob--W** [comment]
Thanks for the report. I analyzed the issue and found that it would also affect other Google sites, e.g. mailto:-links in Gmail. I've fixed the issue and published 4.10 in the Chrome web store and on addons.mozilla.org.

Please update and confirm whether the issue is fixed.

**Comment by malyavkin** [comment]
Yes. Links are working in 4.10, thank you!
