### ISSUE TITLE
First click not sanitised on Google images

### ISSUE THREAD

**Issue by sittaneumayer** [Rob--W/dont-track-me-google#42]
1. Search on _images.google.com_, or on _google.com_ and switch to _images_.
2. Left click on an image to open the sidebar.
3. (Right or left) click on the selected image or the title. (link unsanitised)
4. (Right or left) click on the selected image or the title again. (link sanitised)
5. Repeat from step 2 indefinitely.

Using version 4.23.1 on Firefox 85.0.2.

**Comment by Rob--W** [comment]
Thanks for the detailed reproduction steps.

I followed your steps, and while I am able to see that the tooltip has the old URL, the actual URL that opens (or is copied when the context menu is chosen) is sanitized.

The reason for the tooltip being off is that Google turns the link into an unsanitized URL again (from a `mousedown`, `touchstart` or `focus` handler) after the extension has sanitized it (at `mousedown`). While this doesn't impact the clicked link, it does make the tooltip ugly. I can try to counter this by sanitizing the URL ASAP whenever the mouse pointer moves (or on a timer after sanitizing the link once), but that does slightly increase the complexity of the extension.

Do you still see a problem with the current behavior (i.e. copied/opened link is sanitized even though the tooltip sometimes is not)?

**Comment by sittaneumayer** [comment]
Demonstrating the first click being unsanitised here

https://user-images.githubusercontent.com/79370369/108604868-7d1f0780-73c1-11eb-8975-3a47208e174a.mp4

**Comment by Rob--W** [comment]
Fixed and published as version 4.24, thanks again for your report and STR.
