### ISSUE TITLE
GMail Pop-Ups Broken

### ISSUE THREAD

**Issue by rmccu** [Rob--W/dont-track-me-google#43]
When I try to invoke a pop-up in GMail ("Show Original", "Print", or the pop-out), the popup loads with a blank page and I get this message in gmail: "Grrr! A popup blocker may be preventing the application from opening the page. If you have a popup blocker, try disabling it to open the window."

**Comment by Rob--W** [comment]
This is not caused by the extension. When I disable Don't Track me Google, then I still get a popup blocker warning.

You can choose to permit popups if you want to avoid this warning.

**Comment by rmccu** [comment]
I have pop-ups enabled for the GMail domain. This is something that just started happening maybe a month ago.

If I disable "Don't Track me Google", the pop-ups work correctly. If I enable it, I get the odd behavior and the "Grrr!" message.

I am running Chrome Version 89.0.4389.72 (Official Build) (x86_64).

**Comment by Rob--W** [comment]
I've only tested in Firefox in my previous comment, I'll re-open this until I've managed to check the behavior in Chrome.

> I have pop-ups enabled for the GMail domain. This is something that just started happening maybe a month ago.

Does this mean that the "Grrr!" message still appears even if you've enabled popups?

**Comment by rmccu** [comment]
I just checked and I am getting the same behavior with my personal GMail in Firefox.

I tried to pop-out the email thread for this Github issue. The URL it opened is: https://mail.google.com/mail/u/0/?ui=2&view=btop&ver=i7iyx0m0rxgx&search=inbox&th=%23thread-f%3A1693862921389392625&cvid=2

But it loads a blank browser. Firefox 86.0 (64-bit).

Here is what it looks like:
![Screen Shot 2021-03-10 at 4 18 25 PM](https://user-images.githubusercontent.com/5711475/110711148-45370300-81bc-11eb-83df-986d1235bd8c.png)

**Comment by rmccu** [comment]
If I disable "Don't Track me Google" in Firefox and then reload GMail, then pop-out works.

**Comment by CennoxX** [comment]
Same here, I've the problem with Windows 10 and Firefox, which won't load the content of the (already opened) popup window. The last picture from @rmccu shows it good.

**Comment by Rob--W** [comment]
Thanks for the reports and details. I managed to reproduce and published an update with a fix. It may take a few days before the update is available to everyone, depending on the review policies of the extension stores.
