### ISSUE TITLE
[feature request] Ready User Script

### ISSUE THREAD

**Issue by dnmTX** [Rob--W/dont-track-me-google#44]
Hi Rob @Rob--W. Any chance to provide here ready user script with ability to be fetched and updated,something like:
`// @version .....`
`// @license .......`
`// @downloadURL ......`
`// @updateURL .....`
I'm just trying to offset whatever is not necessary from my Chromium browser to my AdBlocker,which is perfectly capable to run it.
I've been testing it for a while now and didn't see any reason to mess with it,so can be easily moved there.
I'd very much appreciate considering it. Thank you and keep up the good work 👍

**Comment by Rob--W** [comment]
I suppose that I can do that and check it in the repository (e.g. with GitHub pages or on another branch) or publish it on Greasyfork.

**Comment by dnmTX** [comment]
@Rob--W  hosting it here should be fine,i think and thank you so much for doing it 👍 

P.S. Just in case,let me ask the most relevant party 😃 
@ameshkov fetching the user script from GitHub should be fine right? 
Also,if there is anything else that you can suggest to @Rob--W  will be very much appreciated. Thank you 👍

**Comment by ameshkov** [comment]
Hey Rob, long time no see:) Cool userscript, a great candidate for the recommended userscripts article we're going to write son.

**Comment by dnmTX** [comment]
@ameshkov the script is not actually up yet. I was hoping to get your input/suggestions first,but you didn't answer my questions from the previous post ☝️  😄

**Comment by ameshkov** [comment]
Well, there're no special requirements, it just should be a valid userscript

**Comment by dnmTX** [comment]
@Rob--W don't mean to rush or anything,just checking on the progress here 👍

**Comment by Rob--W** [comment]
I'll publish an update later this week.

**Comment by Rob--W** [comment]
Update: I am still evaluating whether to use Greasyfork or publish via Github, haven't made up my mind yet. Will make a decision within a few days.

**Comment by dnmTX** [comment]
@Rob--W  thanks for the update 👍

**Comment by dnmTX** [comment]
@Rob--W just a small suggestion regarding the UserScript.
Consider using regex for the `@match` header,instead of listing every single google country variation.
I can confirm that it's working,using it on my other userscripts,for example i have `https://forum.*/*` and so far didn't miss any website that begins with `forum`.
I do believe using `https://www.google.*/*` will be more then sufficient.
Thank you 👍

**Comment by Rob--W** [comment]
> @Rob--W just a small suggestion regarding the UserScript.
> Consider using regex for the `@match` header,instead of listing every single google country variation.
> I can confirm that it's working,using it on my other userscripts,for example i have `https://forum.*/*` and so far didn't miss any website that begins with `forum`.
> I do believe using `https://www.google.*/*` will be more then sufficient.

I used `@match` because it's a bit more precise and widely supported (e.g. won't match `https://www.google.not-google-example.com`). Its behavior is also consistent with what I'm publishing as an extension.

**Comment by Rob--W** [comment]
Published as https://greasyfork.org/en/scripts/428243-don-t-track-me-google . Let me know if it resolves your issue!

**Comment by dnmTX** [comment]
Rob @Rob--W Thank You 👍 
Just tested it and it's working just fine.
Few questions though:
Regarding any feature updates? You didn't include any download links.
On the script,the last line,i'm not an expert here but just in case to ask.Doesn't need a semicolon or..?
And regarding this:

> The user script cannot be customized (unlike the extension),

What exactly am i missing by using the UserScript instead of the extension. I don't really see any important customisation in the extension besides disabling all those google variations.

**Comment by Rob--W** [comment]
> Rob @Rob--W Thank You 👍 
> Just tested it and it's working just fine.
> Few questions though:
> Regarding any feature updates? You didn't include any download links.

It would be stripped anyway: https://greasyfork.org/en/help/rewriting

> On the script,the last line,i'm not an expert here but just in case to ask.Doesn't need a semicolon or..?

Nope. Semicolons are optional in JS. I usually add them but if they're missing, then it's not going to affect functionality anyway.

> And regarding this:
> 
> > The user script cannot be customized (unlike the extension),
> 
> What exactly am i missing by using the UserScript instead of the extension. I don't really see any important customisation in the extension besides disabling all those google variations.

In case the functionality is too strict, the option can be toggled. I personally don't change the option, but for some it could be a nice alternative to disabling the script (while awaiting an update from me to resolve the broken functionality caused by the script).

**Comment by dnmTX** [comment]
Well....i got that option in AdGuard:
![Capture](https://user-images.githubusercontent.com/34774426/122689804-06690e00-d1eb-11eb-92a2-65fc2982bafa.PNG)

I can toogle it whole day if i wan to..... 😄 
Ok,then what will be the way to check for any new releases?

**Comment by dnmTX** [comment]
And i see there is no special permissions needed `@grant` ,that's kind of odd,but you know better of course 😄

**Comment by Rob--W** [comment]
> Well....i got that option in AdGuard:
> ![Capture](https://user-images.githubusercontent.com/34774426/122689804-06690e00-d1eb-11eb-92a2-65fc2982bafa.PNG)
> 
> I can toogle it whole day if i wan to..... 😄 
> Ok,then what will be the way to check for any new releases?

You can watch this repository.

A regular user script manager performs update checks by downloading the .meta.js file and if it doesn't exist the .user.js file.

> And i see there is no special permissions needed `@grant` ,that's kind of odd,but you know better of course 😄 

`@grant` is only needed for user script-specific APIs. I don't use any.

**Comment by Rob--W** [comment]
> Well, there're no special requirements, it just should be a valid userscript with `@updateURL` and `@downloadURL `

@ameshkov Is your user script implementation compatible with scripts hosted on Greasyfork?

**Comment by dnmTX** [comment]
> You can watch this repository.

I am,but without you to implement the **Release Feature**,there will be no notifications. Like this:
![categories](https://user-images.githubusercontent.com/34774426/122690191-af186d00-d1ed-11eb-8b39-9a41c878cb56.png)

If you do it,it will notify everyone who's watching this repo and it's much preferred by me,this way i can just copy/paste the script part and customize the header as wish.

**Comment by Rob--W** [comment]
What's the point of me publishing a script to Greasyfork if you're going to edit it anyway?

And why do you prefer to use an imprecise wildcard pattern instead of the tested set of Google URLs?

**Comment by dnmTX** [comment]
> What's the point of me publishing a script to Greasyfork if you're going to edit it anyway?

Well let me quote you here,and for the record,i never asked you to publush it there:

> Update: I am still evaluating whether to use Greasyfork or publish via Github, haven't made up my mind yet.

> And why do you prefer to use an imprecise wildcard pattern instead of the tested set of Google URLs?

`*://*.google.com/*` is one of yours,i didn't change it,it's just the one i need.

**Comment by dnmTX** [comment]
Why so mad Rob @Rob--W ? Isn't that the point with UserScripts,to be able to customize?

**Comment by Rob--W** [comment]
> > What's the point of me publishing a script to Greasyfork if you're going to edit it anyway?
> 
> Well let me quote you here 👇 ,and for the record,i never asked you to publush it there:

I've published a script under the assumption that you'd like to have an up-to-date version of the script (due to your mention of `@updateURL` in your first post). Hence my surprise when you immediately detached the script from the source, since that requires you to manually update the script.

I had already published a tool to generate the user script from the source code (see the tools/ directory), and its simply a concatenation of the user script header derived from manifest.json plus the content of contentscript.js. If your only wish is to have a source for copy-pasting the script source (with your custom user script header), just look at contentscript.js here and you don't need to visit Greasyfork.

> > And why do you prefer to use an imprecise wildcard pattern instead of the tested set of Google URLs?
> 
> `*://*.google.com/*` is one of yours,i didn't change it, i left just the one i need.

I see. I mistakenly thought that it was `*.google.*` because that pattern was recently mentioned elsewhere.
If there is an auto-update mechanism in your user script manager, then I suggest to use the script without modifications. Then you'll get the latest version without having to monitor anything.


> Why so mad Rob @Rob--W ? (...) 😞 

Not sure why you think that I am. Because I am not.

**Comment by dnmTX** [comment]
Thank you Rob @Rob--W i'll follow up on your recommendations. 
And just FYI,having it published at Greasyfork will benefit a lots of UserScript enthusiasts for sure,and for me personally i'll
watch the `contentscript.js` for any changes from now on.
I think the feature request is complete but i'm not sure do you want this still open,so i'll leave it to you.
Cheers and stay safe out there 👍

**Comment by dnmTX** [comment]
Rob @Rob--W just to give you some feedback. Initially i had couple times pages crashing on me when they were sitting idle in 
inactive tab with that `Aw, Snap!` error. And just before that happened i could here my laptop's fan ramping up speed.
Trying with `@grant  unsafeWindow` and will keep you posted.
