### ISSUE TITLE
Firefox auth popup issue

### ISSUE THREAD

**Issue by squili** [Rob--W/dont-track-me-google#45]
Platform: Firefox on Linux
Related to: #43

When opening google oauth popups, this extension causes an error to be thrown. You can replicate this easily using api explorer. I've verified this is a don't track me google bug by having it as the only enabled plugin in private mode.

Steps to reproduce:
1. go to https://developers.google.com/drive/api/v3/reference/files/list
2. click execute
3. get "Error authorizing: popup_blocked_by_browser"

Note that this applies to and only to oauth popups. The google oauth playground uses redirects, so it doesn't have the same issue.

**Comment by Rob--W** [comment]
Thanks for your clear report. I've fixed the issue and published an update.
