### ISSUE TITLE
Links in embedded Google search aren't changed

### ISSUE THREAD

**Issue by ZJaume** [Rob--W/dont-track-me-google#47]
Web pages that have embedded Google search still have the Google prefix in the href when using the extension. For example, in https://aclanthology.org/search/?q=machine+translation you can inspect the href in the titles and the prefix is still there.

**Comment by Rob--W** [comment]
"Embedded search" is Google Custom Search. A website needs to explicitly register its website and load a script from Google on their own website. At that point, the script from Google is entrusted with the ability to run scripts in the context of the website.

Any website can do that, so supporting that case would require the extension to have the permission to access every website. I am not going to request too many permissions. Besides, supporting Google Custom Search means that I would have to account for the script running on any web page, which is a significant maintenance burden for me.

**Comment by ZJaume** [comment]
Alright, thanks for the explanation. I guess this can be closed.
