### ISSUE TITLE
google.com/null redirects

### ISSUE THREAD

**Issue by SirnoChan** [Rob--W/dont-track-me-google#48]
I am using this plugin on Firefox TamperMonkey. Recently Google seems to have changed their redirecting strategy. Thus links exposed with this plugin won't work properly if just clicked on in search results. They will become links to the url `www.google.com/null`. But if you open them in new tab, they will be opened normally.

**Comment by Rob--W** [comment]
I cannot reproduce this issue.  The script itself does not generate "null" on its own.

Could you share the exact steps that you are following?
Is this issue also happening in a new browser profile without other extensions or user scripts other than Don't Track Me Google?
