### ISSUE TITLE
Extension Interferes with Correct Google Maps Results

### ISSUE THREAD

**Issue by mollyrealized** [Rob--W/dont-track-me-google#50]
What did you do? (steps to reproduce)

1. Installed Don't Track Me Google extension.
2. Opened https://maps.google.com.
3. Typed "McDonald's near 122 South Michigan Avenue, Chicago, Illinois."

What happened? (actual results)
1. The map zoomed out, but showed McDonald's locations near my home address (the default location where Google Maps opens).

What should have happened? (expected results)
1. The map should've shown McDonald's locations near 122 South Michigan Avenue, Chicago, Illinois.

Disabling the extension made the expected results happen.

**Comment by Rob--W** [comment]
I cannot reproduce the issue. After step 3, I clicked the Search button and/or Enter, and see the expected result, in Chrome and Firefox:

![Screenshot of maps](https://user-images.githubusercontent.com/1365071/216357868-b37c36db-838f-459f-96b6-f7b5e77e7552.png)

If there are some special steps to take, could you be more precise?
To rule out any other causes, try to open a new browser profile, install the extension and visit maps.google.com without logging in. If I need to use a VPN or something to get some more localized version of Google, please let me know. I'm based in The Netherlands, in case it's relevant.

**Comment by mollyrealized** [comment]
I tried it on an entirely different machine; it may be something specific to my synced Firefox profile, though.
Do you have 'home' and 'work' values set in Google Maps?  Just trying to determine what's different.
Do you have any people who you beta test with?  Can they reproduce the issue?

**Comment by Rob--W** [comment]
I'm not logged in, so the Home and Work addresses do not matter.

What do you see if you open a new container tab ( or Private Browsing window - maybe after allowing the extension access to Private Browsing Windows at `about:addons` ), and repeat the same steps?

Could you be very precise with the steps that you have taken? E.g. your steps end with typing a value, but when I do that, Maps does not automatically change the map until I press Enter or click on the button.

**Comment by Rob--W** [comment]
After repeating the steps with a logged-in Google account that has a Home Address set, the same results were observed - the map is centered around the expected search result.

**Comment by mollyrealized** [comment]
Thank you.  I will look back and try to refine this report either this
evening or this weekend.

**Comment by mollyrealized** [comment]
I am sorry for wasting your time -- although I did indeed originally think
through testing it was this extension, it was not.  My apologies.

**Comment by Rob--W** [comment]
No problem, thanks for checking and taking the time to report with the best intentions!
