### ISSUE TITLE
doesn't working to docs.google.com

### ISSUE THREAD

**Issue by mousesalt** [Rob--W/dont-track-me-google#51]
It still queries Google on `docs.google.com/spreadsheet` when adding the suffix `htmlview`.
[the spread](https://docs.google.com/spreadsheets/d/1WuXioTfCsBl2nuJOqtOw7yNjWbrcVrshcBEoxtNL3xg/htmlview) I use of mine.

**Comment by Rob--W** [comment]
The extension does clean up the link when you're interacting with the link, but the tooltip suggested otherwise. I'll fix this.

**Comment by Rob--W** [comment]
I've published 4.28 that fixes this issue.
