### ISSUE TITLE
Can't expand image in Googe Image Search page

### ISSUE THREAD

**Issue by RedDragonx** [Rob--W/dont-track-me-google#6]
When "Don't track me" enabled, image in Googe Image Search page open in new tab instead of expanding them. Can you fix it?

**Comment by Rob--W** [comment]
The image expands when I click on it. Which version of the add-on are you using? Can you do inspect element on the image, take a screenshot of the DOM that appears and post the screenshot here?

**Comment by RedDragonx** [comment]
I'm using 4.12.
What's "DOM" and how can I take a screenshot of it?

**Comment by Rob--W** [comment]
DOM stands for document object model. In Chrome and Firefox, if you right-click anywhere in the page, there is an "Inspect element" context menu option. If you click on this, the developer tools appear and show the visualization of the DOM.

This will help me with seeing whether my "Google images" is the same as yours. For example, when I search for "test" in images.google.com, right-click on a result and choose Inspect element in Firefox, I get the following:

<img width="1288" alt="google-images-test" src="https://cloud.githubusercontent.com/assets/1365071/20259000/c99dd768-aa52-11e6-9e70-c01d29144af1.png">

**Comment by Rob--W** [comment]
The way of taking a screenshot depends on your operating system. On Windows, the Print Screen key on your keyboard will usually create a screenshot. On macOS, use Cmd+Shift+4. On Linux, it depends, but try the Print Screen key as well.

If none of the above tips help, try Googling for how to take a screenshot, or take a photo with your phone or camera. After obtaining a screenshot, just attach it to this Github issue via a comment).

**Comment by RedDragonx** [comment]
I'm using Chrome and this is what I got
![test dom](https://cloud.githubusercontent.com/assets/9276603/20259366/2329f724-aa87-11e6-8e22-2628a8107019.png)

**Comment by logological** [comment]
I can't reproduce this (using the user script version of Don't Track Me Google with Greasemonkey or Scriptish).  How Google Images displays search results, and whether it opens images in the current tab or a new tab, depends on which national Google site I visit, and not on whether the user script is enabled or disabled.

For the image search at google.co.uk, the search results are brought up in the same tab.  Clicking on an image displays it in a light box with "Visit page" and "View image" buttons.  Clicking on either button opens the page or image, respectively, in a new tab.

For the image search at google.de, the search results are brought up in the same tab.  Clicking on an image opens a new, framed page in the same tab, with the left frame showing the page on which the image occurs, and the right frame showing a thumbnail of the image, followed by "Website for this image" and "Full-size image" links.  Clicking on either link opens the page or image, respectively, in the current tab.

Again, the above-noted behaviour is the same whether or not I have the user script enabled.

**Comment by Rob--W** [comment]
Thanks for the screenshot @RedDragonx .

It shows `target="_blank"` on the link. My script blocks default handlers on such links because these links are supposed to open links in a new tab... I will add an exception for Google Images (link pointing to `/imgres`) at the next update.

**Comment by RedDragonx** [comment]
Thank you.

**Comment by RedDragonx** [comment]
One more thing I was just found out when I was looking for a work around with this issue.

In Google Search settings, I have "Open each selected result in a new browser window" option enabled. If I disable this option, images in search result expand just like normal. But if I disable "Don't track me Google" extension, images in search result always expand weather I have this option enable or not.

Hope this help.

**Comment by Rob--W** [comment]
@RedDragonx That is very good to know! Does this setting affect other Google sites, such as Maps or reviews? I have written a fix that specifically targets Google Search (images), but if it affects other sites as well, then maybe I should allow all link clicks to be processed by Google, even if it means that sometimes links become ugly.

I published the update as v 4.13 in the CWS and on AMO. Please verify that the fix works as intended.

**Comment by RedDragonx** [comment]
Yes, it worked. Thank you.

As other Google sites, I only see Google Images Search has this issue so far. If I see another site has this issue, I'll be sure to report it here.
