### ISSUE TITLE
Doesn't work on Google Search ads

### ISSUE THREAD

**Issue by BynariStar** [Rob--W/dont-track-me-google#8]
The ad result links on Google Search don't appear to be caught by this extension. The ads use a slightly different function `google.arwt()` as opposed to the `rwt()` function the regular results use.

**Comment by Rob--W** [comment]
Published fix as v4.15. Please verify that the latest version works as expected.

**Comment by BynariStar** [comment]
The issue is persisting for me on v4.15.

**Comment by Rob--W** [comment]
What steps did you follow to observe the issue?

**Comment by BynariStar** [comment]
After having made sure I was on the latest version, I did a Google search and checked a sponsored link. The sponsored links still retained the onmousedown event and were still being converted.

**Comment by Rob--W** [comment]
I tried the following:

1. Open new Firefox profile.
2. Install Don't Track Me Google (latest version - 4.15 - from AMO).
3. Visit google.nl and search for "vliegreis" (flight, to see adverts from travel sites).
4. Click on the first advert with the left mouse key.
5. While doing the above, I had opened the inspector of the developer tools and observed that the arwt event handler had been removed, and also that I directly navigated to the URL without seeing a rewritten URL.

Can you confirm that you have really installed the latest version of the add-on? If you are using Chrome, then you have to reload Google Search's tab before trying again in that tab.

**Comment by BynariStar** [comment]
I've followed your steps on both Firefox and Chrome, and it appears to be a Chrome-specific issue, as it works fine on Firefox.

**Comment by Rob--W** [comment]
Thanks for the extra detail, I have now confirmed the bug in Chrome and published a fix as version 4.16.

**Comment by BynariStar** [comment]
Works great now. Thank you for your work!
