### ISSUE TITLE
Facebook support

### ISSUE THREAD

**Issue by ypnos** [Rob--W/dont-track-me-google#9]
Thanks for the great plugin!

Would you be interested in also supporting other popular web services that mangle URLs?

Facebook and messenger.com are a prime example. Sometimes clicking on a link on messenger.com even leads you to a "You are leaving Facebook, please confirm" page.

Example link:

> https://www.budgetbytes.com/2017/01/bibimbap-ultimate-bowl-meal/

> https://l.messenger.com/l.php?u=https%3A%2F%2Fwww.budgetbytes.com%2F2017%2F01%2Fbibimbap-ultimate-bowl-meal%2F&h=ATMDKczxocYay-ZLWOaA8UH4dOwRP03eLDAi7fkCNFAP4cFCUFfrxe9uKmyrw7KEl2IfZU8pYb17oGSg-9eKgpOcmbd891DlqUAyqQFOAl3wMr55W8acC65kUKbegRHONCf2cGDT2E60Ow

**Comment by Rob--W** [comment]
I'm not going to add FB to the extension; If I did add Facebook, then I would need to request more permissions, which causes the extension to be disabled until the user approves.

**Comment by ypnos** [comment]
I understand. What do you think about a second extension that addresses Facebook then?
I don't really know about anybody else providing URL unmangling in an extension in general.

**Comment by logological** [comment]
> I don't really know about anybody else providing URL unmangling in an extension in general.

Well, if you are using a user script manager like Greasemonkey, there's [Direct links out](https://openuserjs.org/scripts/nokeya/Direct_links_out).  It seems to work in a similar manner to Don't Track Me Google, but has support for several more websites, including Facebook.

**Comment by ypnos** [comment]
Thank you very much, it works pretty well.

**Comment by anewuser** [comment]
You may be interested in [Redirector](https://github.com/einaregilsson/Redirector) to skip and manipulate URLs like that.

Note: you forgot to close this issue.
